version: '{build}'


branches:
    except:
        - gh-pages


# scripts that run after cloning repository
install:
  - cmd: set MY_VAR=12345         
  - cmd: echo "JCT CMD %MY_VAR%"
  - cmd: echo "%APPVEYOR_BUILD_FOLDER%"
  - sh: echo "FOO"

build_script:
  - mvn clean compile --batch-mode -DskipTest

test_script:
    - sh: mvn clean test --batch-mode || echo "There were test failures" >&2

after_test:
  - cmd: echo "%APPVEYOR_BUILD_FOLDER%"
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\target\surefire-reports\TEST-edu.boisestate.cs471.model.SortingAlgorithmResultsTest.xml))

on_finish:
  - ps: Write-Host 'This is PowerShell'

cache:
  - C:\Users\appveyor\.m2


