version: '{build}'

branches:
    except:
        - gh-pages

build_script:
  - mvn clean compile --batch-mode -DskipTest

test_script:
  - mvn clean test --batch-mode

on_finish:
  - sh: |
      echo "JCT ::: $APPVEYOR_BUILD_FOLDER ::: $APPVEYOR_JOB_ID"
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER" -type f -name 'TEST*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"


cache:
  - C:\Users\appveyor\.m2    
  - C:\maven\

