on: '{build}'

branches:
    except:
        - gh-pages

build_script:
  - mvn clean compile --batch-mode -DskipTest

test_script:
  - mvn clean test --batch-mode

after_test:
  - echo "JCT ::: TRACE"
  - sh: |
        echo "JCT ::: TRACE - SH"
cache:
  - C:\Users\appveyor\.m2

