version: '{build}'


branches:
    except:
        - gh-pages


# scripts that run after cloning repository
install:
  - cmd: set MY_VAR=12345         
  - cmd: echo "JCT CMD %MY_VAR%"
  - cmd: echo "%APPVEYOR_BUILD_FOLDER%"
  - sh: echo "FOO"

build_script:
  - mvn clean compile --batch-mode -DskipTest

test_script:
    - mvn clean test --batch-mode

on_finish:
  - ps: Write-Host 'This is PowerShell'

cache:
  - C:\Users\appveyor\.m2


