version: '{build}'


branches:
    except:
        - gh-pages


# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell'
  # batch commands start from cmd:
  - cmd: echo This is batch again
  - cmd: set MY_VAR=12345         
  - cmd: echo "JCT CMD %MY_VAR%"
  - sh: echo "JCT SH $MY_VAR"
  - ps: $MY_VAR
  - ps: $APPVEYOR_BUILD_FOLDER
  - ps: $APPVEYOR_JOB_ID

build_script:
  - mvn clean compile --batch-mode -DskipTest

test_script:
    - mvn clean test --batch-mode

on_finish:
  - ps: Write-Host 'This is PowerShell'

cache:
  - C:\Users\appveyor\.m2


