version: '{build}'

image: ubuntu

branches:
    except:
        - gh-pages

install:
    - sh: echo "JCT ::: TRACE"

build_script:
  - mvn clean compile --batch-mode -DskipTest

test_script:
    - mvn clean test --batch-mode

cache:
  - C:\Users\appveyor\.m2

